
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpgaRJDs2IN8NpbAjkHW7XAPKTD-OkNXk',
    appId: '1:203115439159:web:c14db1dcb5a721fcdd8bb2',
    messagingSenderId: '203115439159',
    projectId: 'fir-sem2',
    authDomain: 'fir-sem2.firebaseapp.com',
    storageBucket: 'fir-sem2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqWvUOR97YdUaWl7YX3FzADnYiFbm1Q0',
    appId: '1:203115439159:android:53d987ea49cd7811dd8bb2',
    messagingSenderId: '203115439159',
    projectId: 'fir-sem2',
    storageBucket: 'fir-sem2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2cuHxk3ZHLhJozoZUFYYW1mj6wLRMvY',
    appId: '1:203115439159:ios:8355da7449b0fc00dd8bb2',
    messagingSenderId: '203115439159',
    projectId: 'fir-sem2',
    storageBucket: 'fir-sem2.appspot.com',
    iosClientId:
        '203115439159-9ncj41jfffvnanp9ttpb2epqgeo1s96g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2cuHxk3ZHLhJozoZUFYYW1mj6wLRMvY',
    appId: '1:203115439159:ios:8355da7449b0fc00dd8bb2',
    messagingSenderId: '203115439159',
    projectId: 'fir-sem2',
    storageBucket: 'fir-sem2.appspot.com',
    iosClientId:
        '203115439159-9ncj41jfffvnanp9ttpb2epqgeo1s96g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}


